# Generated by Django 4.2.9 on 2024-04-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cake_cart_cartitem_customizeoption_order_orderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('egg_version', models.CharField(max_length=10)),
                ('toppings', models.TextField()),
                ('shape', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('mobileNo', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='cake',
            name='flavour',
            field=models.CharField(default='Vanilla', max_length=10),
        ),
        migrations.AddField(
            model_name='cake',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cake',
            field=models.ManyToManyField(related_name='cart', to='myapp.cake'),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order', to='myapp.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('cash', 'Cash On Delivery')], default='debit_card', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='CustomizeOption',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cake'),
        ),
        migrations.AddField(
            model_name='cakecustomization',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customization',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cakecustomization'),
        ),
        migrations.AddField(
            model_name='order',
            name='cake_customization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.cakecustomization'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
    ]
