# Generated by Django 4.2.9 on 2024-04-26 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cakecustomization_customer_remove_orderitem_cake_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cakecustomization'),
        ),
    ]
