# Generated by Django 4.2.9 on 2024-04-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cake_customization',
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='cake_customization',
            field=models.ManyToManyField(related_name='order', to='myapp.cakecustomization'),
        ),
    ]
