# Generated by Django 4.2.9 on 2024-05-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_order_cake_customization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cake_customization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cakecustomization'),
        ),
    ]
