# Generated by Django 4.2.9 on 2024-05-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.store'),
        ),
    ]
